import "./tag/app.tag";
import "./tag/view-editor.tag";
import "./tag/editor-menubar.tag";
import "./tag/editor-palette.tag";
import "./tag/editor-palette-section.tag";
import "./tag/editor-main.tag";
import "./tag/editor-toolbar.tag";
import "./tag/components/file-save-dialog.tag"
import "./css/app.scss"
